package Prova;
import static Prova.tela.contTela;
import static Prova.tela.perguntas;
import static Prova.tela.prova;
import java.awt.Color;
import java.awt.event.ActionEvent;
/**
 *
 * @author Joao Antonio
 */
public class telaPergunta extends javax.swing.JInternalFrame {
    Pergunta pergunta;
    Correcao correcao;
    /**
     * Creates new form telaPergunta
     */
    public telaPergunta() {
        initComponents();
        jLabel1.setText("Pergunta: "+(contTela+1));
        pergunta=perguntas.get(contTela);
        iniciaPergunta();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnProximaTela = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbEnunciado1 = new javax.swing.JLabel();
        lbEnunciado2 = new javax.swing.JLabel();
        lbEnunciado3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbOpcao4 = new javax.swing.JRadioButton();
        rbOpcao3 = new javax.swing.JRadioButton();
        rbOpcao2 = new javax.swing.JRadioButton();
        rbOpcao1 = new javax.swing.JRadioButton();
        pnResultado = new javax.swing.JPanel();
        btnCorrige = new javax.swing.JButton();

        setMaximizable(true);
        setTitle("Pergunta");

        btnProximaTela.setText("Proxima");
        btnProximaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaTelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pergunta: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbEnunciado1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbEnunciado2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lbEnunciado3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEnunciado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEnunciado2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                    .addComponent(lbEnunciado3, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEnunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEnunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEnunciado3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(rbOpcao4);
        rbOpcao4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        buttonGroup1.add(rbOpcao3);
        rbOpcao3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        buttonGroup1.add(rbOpcao2);
        rbOpcao2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        buttonGroup1.add(rbOpcao1);
        rbOpcao1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        rbOpcao1.setSelected(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOpcao1, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                    .addComponent(rbOpcao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOpcao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOpcao4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOpcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOpcao4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnResultado.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        javax.swing.GroupLayout pnResultadoLayout = new javax.swing.GroupLayout(pnResultado);
        pnResultado.setLayout(pnResultadoLayout);
        pnResultadoLayout.setHorizontalGroup(
            pnResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        pnResultadoLayout.setVerticalGroup(
            pnResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        btnCorrige.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnCorrige.setText("Corrige");
        btnCorrige.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorrigeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProximaTela))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnProximaTela))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaTelaActionPerformed
        gerarTela();
    }//GEN-LAST:event_btnProximaTelaActionPerformed

    private void btnCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorrigeActionPerformed
        corrige();
    }//GEN-LAST:event_btnCorrigeActionPerformed
    public void iniciaPergunta(){
        btnProximaTela.setEnabled(false);
        if(pergunta.getEnunciado().length()<59){
            lbEnunciado1.setText(pergunta.getEnunciado());
        }else{
            String texto=pergunta.getEnunciado();
            lbEnunciado1.setText(texto.substring(0, 59));
            if(texto.length()>118){
                lbEnunciado2.setText(texto.substring(60,118));
                if(texto.length()>119)
                lbEnunciado3.setText(texto.substring(119));
            }
            else{
                lbEnunciado2.setText(texto.substring(60));
            }
        }
        rbOpcao1.setText(pergunta.getOpcao1());
        rbOpcao2.setText(pergunta.getOpcao2());
        rbOpcao3.setText(pergunta.getOpcao3());
        rbOpcao4.setText(pergunta.getOpcao4());
    }
    public void gerarTela(){
        if(contTela+1==perguntas.size()){
            this.dispose();
            //colocar o gerar relatorio aqui
        }
        else{
            tela.gerarTela();
            this.dispose();
        }
    }
    public void corrige(){
        String a,b,c,d;
        a=rbOpcao1.getText();
        b=rbOpcao2.getText();
        c=rbOpcao3.getText();
        d=rbOpcao4.getText();
        
        String resposta=pergunta.getReposta();
        if(rbOpcao1.isSelected()==true){
            if(resposta.equals(a)){
                correcao=new Correcao(pergunta,a,"Certo");
                prova.addCorrecao(correcao);
                btnProximaTela.setEnabled(true);
                pnResultado.setBackground(Color.green);
                btnCorrige.setEnabled(false);
            }
            else{
                correcao=new Correcao(pergunta,a,"Errado");
                prova.addCorrecao(correcao);
                btnProximaTela.setEnabled(true);
                pnResultado.setBackground(Color.red);
                btnCorrige.setEnabled(false);
            }
        }
        else{
            if(rbOpcao2.isSelected()==true){
                if(resposta.equals(b)){
                    correcao=new Correcao(pergunta,b,"Certo");
                    prova.addCorrecao(correcao);
                    btnProximaTela.setEnabled(true);
                    pnResultado.setBackground(Color.green);
                    btnCorrige.setEnabled(false);
                }
                else{
                    correcao=new Correcao(pergunta,b,"Errado");
                    prova.addCorrecao(correcao);
                    btnProximaTela.setEnabled(true);
                    pnResultado.setBackground(Color.red);
                    btnCorrige.setEnabled(false);
                }
            }
            else{
                if(rbOpcao3.isSelected()==true){
                    if(resposta.equals(c)){
                        correcao=new Correcao(pergunta,c,"Certo");
                        prova.addCorrecao(correcao);
                        btnProximaTela.setEnabled(true);
                        pnResultado.setBackground(Color.green);
                        btnCorrige.setEnabled(false);
                    }
                    else{
                        correcao=new Correcao(pergunta,c,"Errado");
                        prova.addCorrecao(correcao);
                        btnProximaTela.setEnabled(true);
                        pnResultado.setBackground(Color.red);
                        btnCorrige.setEnabled(false);
                    }
                }
                else{
                    if(rbOpcao4.isSelected()==true){
                        if(resposta.equals(d)){
                            correcao=new Correcao(pergunta,d,"Certo");
                            prova.addCorrecao(correcao);
                            btnProximaTela.setEnabled(true);
                            pnResultado.setBackground(Color.green);
                            btnCorrige.setEnabled(false);
                        }
                        else{
                            correcao=new Correcao(pergunta,d,"Errado");
                            prova.addCorrecao(correcao);
                            btnProximaTela.setEnabled(true);
                            pnResultado.setBackground(Color.red);
                            btnCorrige.setEnabled(false);
                        }
                    }
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnProximaTela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbEnunciado1;
    private javax.swing.JLabel lbEnunciado2;
    private javax.swing.JLabel lbEnunciado3;
    private javax.swing.JPanel pnResultado;
    private javax.swing.JRadioButton rbOpcao1;
    private javax.swing.JRadioButton rbOpcao2;
    private javax.swing.JRadioButton rbOpcao3;
    private javax.swing.JRadioButton rbOpcao4;
    // End of variables declaration//GEN-END:variables
}
